version: "3.8"

services:
  db-test:
    image: postgres:14.2-alpine
    restart: always
    container_name: 'db-test'
    networks:
      - tests
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: TCAuthTest
    ports:
      - 10001:5432
      
  tests:
    build: 
      dockerfile: Tests/Dockerfile
      context: .
    depends_on:
      - db-test
    networks:
      - tests
    volumes:
      - ./logs/tc-auth-tests:/var/log/tc-auth-tests
    
networks:
  tests: {}
