services:
  auth-db-test:
    image: postgres:14.2-alpine
    restart: always
    container_name: 'auth-db-test'
    networks:
      - tests
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: TCAuthTest
    ports:
      - 11001:5432
      
  auth-tests:
    container_name: 'auth-tests'
    build: 
      dockerfile: Tests/Dockerfile
      context: .
    depends_on:
      - auth-db-test
    networks:
      - tests
    volumes:
      - ./logs/tc-auth-tests:/var/log/tc-auth-tests
    
networks:
  tests: {}
