name: E2E Tests Against Prod

on:
  workflow_call:

jobs:
  e2e-test-against-prod:
    # need to run on our own runners that we have access to the logs later on our servers
    # otherwise, if we use shared runners they store log files in their VMs which we cannot access
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
      
    - name: Download Karate JAR
      run: |
        curl -L https://github.com/karatelabs/karate/releases/download/v1.5.1/karate-1.5.1.jar -o karate.jar

    - name: Run E2E Tests Against Local Env
      run: |
        # Redirecting logs to a file on the server
        # Example of a filename: "/var/log/inner-circle/e2e/2026-07-22-inner-circle-time-api-run-27459153975-job-81169369662.log"
        # Learn more about '2>&1': https://stackoverflow.com/a/42919998
        # In essence it merges output and error streams and doesn't show errors in the terminal to avoid leakage of secrets in the pipeline
        java -jar karate.jar . > "/var/log/inner-circle/e2e/$(date +%F)-${{ github.event.repository.name }}-run-${{ github.run_id }}-job-${{ job.check_run_id }}.log" 2>&1
      env:
        "AUTH_FIRST_TENANT_LOGIN_WITH_ALL_PERMISSIONS": ${{ secrets.INNER_CIRCLE_PROD_AUTH_FIRST_TENANT_LOGIN_WITH_ALL_PERMISSIONS }}
        "AUTH_FIRST_TENANT_PASSWORD_WITH_ALL_PERMISSIONS": ${{ secrets.INNER_CIRCLE_PROD_AUTH_FIRST_TENANT_PASSWORD_WITH_ALL_PERMISSIONS }}
        "API_ROOT_URL": ${{ secrets.INNER_CIRCLE_PROD_AUTH_API_ROOT_URL }}
        "CORS_ALLOWED_ORIGINS": ${{ secrets.INNER_CIRCLE_PROD_BASE_URL }}
        "SHOULD_USE_FAKE_EXTERNAL_DEPENDENCIES": "false"